image: czimnick/recordsystem-dev:latest
services:
before_script:
stages:
  - build
  - test
  - deploy

job1:
  stage: build
  script:
    - echo "test"
    - git submodule update --init --recursive
    - ./create_projects.sh
    - ./build_projects.sh Release
  only:
    - master
  tags:
    - docker