image: ubuntu:latest
services:
before_script:
  - apt-get update
  - apt-get upgrade -y
  - apt-get install git -y

stages:
  - build
  - test
  - deploy

job1:
  stage: build
  script:
    - echo "test"
  only:
    - master
  tags:
    - docker