image: czimnick/recordsystem-dev:latest
services:
before_script:
stages:
  - build
  - test
  - deploy
ubuntu-build:
  stage: build
  script:
    - echo "test"
    - git submodule update --init --recursive
    - ./create_projects.sh
    - ./build_projects.sh Release
  only:
    - master
  tags:
    - docker
arm-build:
  stage: build
  script:
    - git submodule update --init --recursive
    - ./create_projects.sh
    - ./build_projects.sh Release
  only:
    - master
  tags:
    - arm
windows-build:
  stage: build
  script:
    - git submodule update --init --recursive && call create_projects.bat && call build_projects.bat Release
  only:
    - master
  tags:
    - windows
osx-build:
  stage: build
  script:
    - git submodule update --init --recursive
    - ./create_projects.sh
    - ./build_projects.sh Release
  only:
    - master
  tags:
    - osx
