image: czimnick/recordsystem-dev:latest
services:
before_script:
  - apt-get install git -y

stages:
  - build
  - test
  - deploy

job1:
  stage: build
  script:
    - echo "test"
  only:
    - master
  tags:
    - docker