# Enable C++ support
language: cpp
os:
  - linux
  - osx
compiler:
  - gcc
git:
  submodules: false
before_install:
  - git submodule update --init
  - git fetch -t
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt-get -qq install -y libgd2-xpm ia32-libs ia32-libs-multiarch; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt-get -qq install -y gcc-multilib libstdc++6-4.4-dev gcc-4.4-multilib g++-4.4-multilib g++-multilib python p7zip p7zip-full build-essential; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install p7zip; fi
script:
  - ./create_projects.sh && ./build_projects.sh Release
